name: Mac OSX CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  schedule:
#    - cron: '0 6 * * 6'
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1.5.3
      with:
        crystal: latest
    - name: Install dependencies
      run: brew install fftw
    - name: Run tests
      run: crystal spec
